# Generated by Django 3.2.23 on 2023-11-30 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_reviewotheruserprofiles_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewotheruserprofiles',
            name='rating',
            field=models.IntegerField(default=1),
        ),
    ]
