# Generated by Django 3.2.23 on 2023-11-17 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blurbs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blurbs',
            name='category',
            field=models.CharField(choices=[('Spring', 'Spring'), ('Summer', 'Summer'), ('Autumn', 'Autumn'), ('Winter', 'Winter')], default='Which season?', max_length=8),
        ),
    ]
