# Generated by Django 3.2.23 on 2023-11-18 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blurbs', '0003_alter_blurbs_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blurbs',
            name='category',
            field=models.CharField(choices=[('Spring', 'Spring'), ('Summer', 'Summer'), ('Autumn', 'Autumn'), ('Winter', 'Winter')], default='Spring', max_length=100),
        ),
    ]
